# Generated by Django 6.0.7 on 2026-08-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_increase_callback_secret_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="question",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("provisioning", "Provisioning sandbox"),
                    ("cloning", "Cloning"),
                    ("running", "Running"),
                    ("reporting", "Reporting"),
                    ("needs_input", "Waiting for user input"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
