"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import tomllib
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

#todo: maybe pass form env (docker, kuber)
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-dev-only-key")
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")
_allowed_hosts_raw = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(",") if h.strip()] if _allowed_hosts_raw else ["localhost", "127.0.0.1"]


__version__ = "0.3.0-rc.4"

def get_app_version():
    try:
        with open(BASE_DIR / "pyproject.toml", "rb") as f:
            _pyproject = tomllib.load(f)
            __version__ = _pyproject["project"]["version"]
    except (FileNotFoundError, KeyError, tomllib.TOMLDecodeError):
        pass
    return __version__

__version__ = get_app_version()

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'jobs',
    'apps.ingestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# The web service writes the Task row and the Celery worker reads it back from
# another container, so BOTH must resolve to the *same* file.  DATABASE_PATH
# makes that explicit for deployments where /app is not a shared bind mount —
# if the two services end up on different files the worker sees a migrated but
# empty database and every job dies with "Task not found in DB".

DATABASE_PATH = Path(os.environ.get("DATABASE_PATH") or BASE_DIR / "data" / "db.sqlite3")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATABASE_PATH,
        "OPTIONS": {
            # WAL lets the worker read while the web process writes (and makes a
            # freshly committed row immediately visible to the other process)
            # instead of the two blocking each other on the rollback journal.
            "init_command": "PRAGMA journal_mode=WAL;PRAGMA synchronous=NORMAL;",
            # Wait for a busy writer rather than failing with "database is locked".
            "timeout": 30,
        },
    }
}


# Celery
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/1")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/2")
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_ROUTES = {
    "jobs.tasks.execute_task": {"queue": "execute"},
}
# Number of task slots a worker process runs in parallel.  Celery reads this
# (via the CELERY_ namespace → ``worker_concurrency``) at worker startup, so it
# applies to `celery -A config worker` without a --concurrency flag; passing
# --concurrency on the command line still wins over it.  Each slot can hold a
# full sandbox container, so on constrained hosts keep this at 1 to serialise
# execution and avoid OOM-killed sandboxes.
try:
    CELERY_WORKER_CONCURRENCY = max(1, int(os.environ.get("CELERY_WORKER_CONCURRENCY", "1")))
except ValueError:
    CELERY_WORKER_CONCURRENCY = 1

# Redis
REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")

# Sandbox container settings
SANDBOX_IMAGE = os.environ.get("SANDBOX_IMAGE", "jiffy-sandbox:1.2.0")

# Hard memory limit for a sandbox container (Docker size string: b/k/m/g).
# ``SANDBOX_MEM_LIMIT`` is the older name and is still honoured as a fallback.
SANDBOX_MEMORY_LIMIT = os.environ.get(
    "SANDBOX_MEMORY_LIMIT",
    os.environ.get("SANDBOX_MEM_LIMIT", "2g"),
)
# Combined memory + swap limit.  Docker requires this to be passed alongside
# the memory limit; the difference between the two is how much the container
# may spill into swap instead of being OOM-killed the moment RAM runs out.
# MUST be >= SANDBOX_MEMORY_LIMIT — if it isn't, the Gateway logs a warning and
# falls back to 2x the memory limit.  Use "-1" for unlimited swap.
SANDBOX_MEMORY_SWAP_LIMIT = os.environ.get("SANDBOX_MEMORY_SWAP_LIMIT", "4g")
# CPU quota for a sandbox container, in (fractional) cores — e.g. "1.5".
SANDBOX_CPU_LIMIT = os.environ.get("SANDBOX_CPU_LIMIT", "1.5")
# Backwards-compatible alias; prefer SANDBOX_MEMORY_LIMIT.
SANDBOX_MEM_LIMIT = SANDBOX_MEMORY_LIMIT

# --- LLM provider credentials forwarded into the sandbox --------------------
# `opencode.json` (injected into the container by _inject_opencode_config)
# references these, so the agent process needs them in its environment.
# They are passed as container env only — never persisted to the DB or baked
# into the image.  Unset/blank values are simply not forwarded.
SANDBOX_AGENT_ENV_PASSTHROUGH = ("OPEN_API_BASE_URL", "OPEN_API_KEY")

# --- Package-manager memory pressure inside the sandbox ---------------------
# Heavy `npm install` / `pnpm install` runs are the usual cause of a sandbox
# being OOM-killed (exit 137).  These caps are applied to the container's
# environment (and pnpm's own config) before any install command runs.
#
# Node heap cap in MiB.  Empty/unset = derive it from SANDBOX_MEMORY_LIMIT
# (half the container memory, floor 512 MiB) so it tracks the memory limit
# automatically.
SANDBOX_NODE_MAX_OLD_SPACE_MB = os.environ.get("SANDBOX_NODE_MAX_OLD_SPACE_MB", "").strip()
# How many install/network/build jobs package managers may run in parallel.
try:
    SANDBOX_PACKAGE_CONCURRENCY = max(1, int(os.environ.get("SANDBOX_PACKAGE_CONCURRENCY", "2")))
except ValueError:
    SANDBOX_PACKAGE_CONCURRENCY = 2

# How long a single agent run may take before the Gateway gives up on it.
# Enforced by the Gateway itself (it polls the exec state), so it is a real
# budget rather than a side effect of whatever request timeout the Docker
# client or an intermediate socket proxy happens to use.
try:
    SANDBOX_AGENT_TIMEOUT_SECONDS = max(60, int(os.environ.get("SANDBOX_AGENT_TIMEOUT", "3600")))
except ValueError:
    SANDBOX_AGENT_TIMEOUT_SECONDS = 3600

# Whether to stop and remove sandbox containers after each job.
# Set to "false" to leave containers running for debugging.
SANDBOX_CLEANUP = os.environ.get("JIFFY_SANDBOX_CLEANUP", "true").lower() in ("true", "1", "yes")

# Whether to restrict sandbox container network egress to an allow-list.
# Default is restricted — the sandbox must never silently run unrestricted.
# Set to "false" to fully disable the restriction (open network) for debugging.
SANDBOX_NETWORK_RESTRICTED = os.environ.get("JIFFY_SANDBOX_NETWORK_RESTRICTED", "true").lower() in ("true", "1", "yes")

# Network allow-list for sandbox containers (hostnames).
# Containers can only reach hosts matching these entries when network
# restriction is active.  At minimum, include the package registries for
# Python/Node/Go/Rust plus the git remote hosts for each provider in use.
_default_network_allowlist = ",".join([
    "pypi.org",
    "files.pythonhosted.org",
    "registry.npmjs.org",
    "crates.io",
    "static.crates.io",
    "proxy.golang.org",
    "sum.golang.org",
    "github.com",
    "api.github.com",
    "objects.githubusercontent.com",
    "codeload.github.com",
    "gitlab.com",
    "gitea.com",
])
# Full override of the default allow-list.  Unset to use the defaults above.
SANDBOX_NETWORK_ALLOWLIST = [
    h.strip()
    for h in os.environ.get("SANDBOX_NETWORK_ALLOWLIST", _default_network_allowlist).split(",")
    if h.strip()
]
# Additional hosts appended to the allow-list on top of the defaults (or the
# SANDBOX_NETWORK_ALLOWLIST override).  Use this for self-hosted git server
# instances and the LLM provider endpoint OpenCode is configured to use —
# both vary per install and cannot be hardcoded.
SANDBOX_NETWORK_ALLOWLIST_EXTRA = [
    h.strip()
    for h in os.environ.get("SANDBOX_NETWORK_ALLOWLIST_EXTRA", "").split(",")
    if h.strip()
]
# Effective, de-duplicated allow-list used at container start.
_effective_allowlist: list[str] = []
_seen_hosts: set[str] = set()
for _host in SANDBOX_NETWORK_ALLOWLIST + SANDBOX_NETWORK_ALLOWLIST_EXTRA:
    _host = _host.strip().lower()
    if _host and _host not in _seen_hosts:
        _seen_hosts.add(_host)
        _effective_allowlist.append(_host)
SANDBOX_NETWORK_EFFECTIVE_ALLOWLIST = _effective_allowlist


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "jobs.tasks": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "jobs.execution": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "apps.ingestion": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "config.celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# --- Ingestion request body size ------------------------------------------
# An issue thread handed to Jiffy is the *entire* conversation — issue body
# plus every comment — so a busy thread can be megabytes of text.  Django's
# default ``DATA_UPLOAD_MAX_MEMORY_SIZE`` (2.5 MiB) would reject those with a
# ``RequestDataTooBig`` before the ingestion view ever sees them, silently
# capping how much of an issue can reach the agent.  Uncapped by default;
# set ``MAX_INGEST_BODY_BYTES`` to a positive byte count to re-impose a limit.
try:
    _max_ingest_body = int(os.environ.get("MAX_INGEST_BODY_BYTES", "0"))
except ValueError:
    _max_ingest_body = 0
DATA_UPLOAD_MAX_MEMORY_SIZE = _max_ingest_body if _max_ingest_body > 0 else None

# JSON payloads are read as a single body, not as form fields, so the field
# count cap only ever gets in the way here.
DATA_UPLOAD_MAX_NUMBER_FIELDS = None


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'Jiffy API Gateway',
    'DESCRIPTION': 'Central server for Jiffy: receives task requests, runs an LLM coding agent, and reports back.',
    'VERSION': __version__,
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [{'X-JIFFY-TOKEN ': []}],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'X-JIFFY-TOKEN ': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'X-JIFFY-TOKEN ',
            },
        },
    },
}
